BTN_PROFILE = "👤 Профиль"
BTN_CONFIGS = "🔑 Конфиги"
BTN_BUY = "💳 Купить / Продлить"
BTN_GUIDE = "📖 Инструкция"
BTN_SUPPORT = "🆘 Поддержка"
BTN_ADMIN = "⚙️ Админка"

CB_BUY_7 = "buy_7"
CB_BUY_30 = "buy_30"
CB_SHOW_INSTRUCTION = "show_instruction"
CB_SHOW_BUY_MENU = "show_buy_menu"
CB_CONFIG_DEVICE_PREFIX = "config_device_"
CB_BACK_TO_PROFILE = "back_to_profile"
CB_BACK_TO_CONFIGS = "back_to_configs"
CB_BACK_TO_ADMIN = "back_to_admin"

CB_ADMIN_LIST = "admin_list"
CB_ADMIN_STATS = "admin_stats"
CB_ADMIN_SYNC = "admin_sync_awg"
CB_ADMIN_CLEAN_ORPHANS = "admin_clean_orphans"
CB_ADMIN_BROADCAST = "admin_broadcast"

CB_BROADCAST_CONFIRM = "broadcast_confirm"
CB_BROADCAST_CANCEL = "broadcast_cancel"
